### ISSUE TITLE
Failed to create parent directory 

### ISSUE THREAD

**Issue by OskarD** [phax/peppol-smp-server#14]
I get the following error i my tomcat7 localhost.log when I try to deploy the webapp:

> Feb 08, 2016 11:41:12 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class com.helger.peppol.smpserver.servlet.SMPWebAppListener
com.helger.commons.exception.InitializationException: Failed to init PhotonSecurityManager
	at com.helger.photon.security.mgr.PhotonSecurityManager.onAfterInstantiation(PhotonSecurityManager.java:116)
	at com.helger.commons.scope.singleton.AbstractSingleton.getSingleton(AbstractSingleton.java:621)
	at com.helger.commons.scope.singleton.AbstractGlobalSingleton.getGlobalSingleton(AbstractGlobalSingleton.java:66)
	at com.helger.photon.security.mgr.PhotonSecurityManager.getInstance(PhotonSecurityManager.java:146)
	at com.helger.photon.security.mgr.PhotonSecurityManager.getUserMgr(PhotonSecurityManager.java:176)
	at com.helger.peppol.smpserver.app.AppSecurity.init(AppSecurity.java:34)
	at com.helger.peppol.smpserver.servlet.SMPWebAppListener.initGlobals(SMPWebAppListener.java:109)
	at com.helger.photon.core.servlet.AbstractWebAppListenerMultiApp.afterContextInitialized(AbstractWebAppListenerMultiApp.java:101)
	at com.helger.photon.core.servlet.WebAppListener.contextInitialized(WebAppListener.java:505)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.helger.photon.basic.app.dao.impl.DAOException: The DAO of class com.helger.photon.basic.audit.AuditManager failed to create parent directory '/var/lib/tomcat7/conf/audits/2016/02': [FileIOError@0x4caf8c12: operation=CREATE_DIR_RECURSIVE; ecode=OPERATION_FAILED; file1=/var/lib/tomcat7/conf/audits/2016/02]
	at com.helger.photon.basic.app.dao.impl.AbstractSimpleDAO.getSafeFile(AbstractSimpleDAO.java:222)
	at com.helger.photon.basic.app.dao.impl.AbstractSimpleDAO.initialRead(AbstractSimpleDAO.java:292)
	at com.helger.photon.basic.audit.AuditManager.<init>(AuditManager.java:222)
	at com.helger.photon.security.mgr.PhotonSecurityManager.onAfterInstantiation(PhotonSecurityManager.java:82)
	... 21 more

I bet I did something stupid, but I can't figure out what... Does anyone have a clue?

**Comment by phax** [comment]
The server was trying to create the folder `/var/lib/tomcat7/conf/audits/2016/02` but failed.
You need to give the SMP server write access to a certain folder on disk. Therefore you need to set the `webapp.datapath` property in the file `webapp.properties` to a directory where the user that is running Tomcat has write access.

**Comment by OskarD** [comment]
I created a 2016 directory in `/var/lib/tomcat7/conf/audits/` and now it works :) Thank you Philip

**Comment by phax** [comment]
The base folder seems to be `/var/lib/tomcat7/conf/` - so please ensure this folder is present and the user has access. Anyway I doubt that runtime data should be inside `/var/lib/tomcat7/` - Maybe `/etc/peppol-smp` (or so) would be better.
