### ISSUE TITLE
Technical error on SML connection

### ISSUE THREAD

**Issue by phax** [phax/peppol-smp-server#35]
Maybe because Metro is part of Tomcat??
```
[2016-10-18T16:19:52,264] [SMP-SERVER] [ERROR] [ajp-nio-127.0.0.1-8009-exec-13] Could not create business XXX in SML -- com.helger.peppol.smpserver.smlhook.RegistrationHookWriteToSML.createServiceGroup(RegistrationHookWriteToSML.java:159)
javax.xml.ws.WebServiceException: com.sun.xml.ws.util.ServiceConfigurationError: com.sun.xml.ws.api.policy.PolicyResolverFactory: Provider com.sun.xml.ws.policy.parser.WsitPolicyResolverFactory is specified in jar:file:/data0/web/tomcat/lib/webservices-rt.jar!/META-INF/services/com.sun.xml.ws.api.policy.PolicyResolverFactorybut could not be instantiated: java.lang.ClassCastException: Cannot cast com.sun.xml.ws.policy.parser.WsitPolicyResolverFactory to com.sun.xml.ws.api.policy.PolicyResolverFactory
	at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:367) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:320) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:229) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:211) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:207) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:112) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at javax.xml.ws.Service.<init>(Service.java:92) ~[?:2.2.0-1]
	at com.helger.peppol.smlclient.participant.ManageBusinessIdentifierService.<init>(ManageBusinessIdentifierService.java:40) ~[peppol-sml-client-5.1.5-SNAPSHOT.jar:5.1.5-SNAPSHOT]
	at com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.createWSPort(ManageParticipantIdentifierServiceCaller.java:123) ~[peppol-sml-client-5.1.5-SNAPSHOT.jar:5.1.5-SNAPSHOT]
	at com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.create(ManageParticipantIdentifierServiceCaller.java:193) ~[peppol-sml-client-5.1.5-SNAPSHOT.jar:5.1.5-SNAPSHOT]
	at com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.create(ManageParticipantIdentifierServiceCaller.java:158) ~[peppol-sml-client-5.1.5-SNAPSHOT.jar:5.1.5-SNAPSHOT]
	at com.helger.peppol.smpserver.smlhook.RegistrationHookWriteToSML.createServiceGroup(RegistrationHookWriteToSML.java:147) [peppol-smp-server-library-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
	at com.helger.peppol.smpserver.data.xml.mgr.XMLServiceGroupManager.createSMPServiceGroup(XMLServiceGroupManager.java:87) [peppol-smp-server-xml-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
	at com.helger.peppol.smpserver.data.xml.mgr.XMLServiceGroupManager.createSMPServiceGroup(XMLServiceGroupManager.java:51) [peppol-smp-server-xml-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
	at com.helger.peppol.smpserver.ui.secure.PageSecureServiceGroups.validateAndSaveInputParameters(PageSecureServiceGroups.java:403) [classes/:?]
	at com.helger.peppol.smpserver.ui.secure.PageSecureServiceGroups.validateAndSaveInputParameters(PageSecureServiceGroups.java:96) [classes/:?]
	at com.helger.photon.uicore.page.AbstractWebPageForm.fillContent(AbstractWebPageForm.java:1213) [ph-oton-uicore-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.photon.uicore.page.AbstractWebPage.getContent(AbstractWebPage.java:156) [ph-oton-uicore-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.peppol.smpserver.ui.pub.SMPRendererPublic.getPageContent(SMPRendererPublic.java:231) [classes/:?]
	at com.helger.peppol.smpserver.ui.secure.SMPRendererSecure.getContent(SMPRendererSecure.java:148) [classes/:?]
	at com.helger.peppol.smpserver.ui.secure.SMPRendererSecure.getContent(SMPRendererSecure.java:65) [classes/:?]
	at com.helger.photon.core.app.layout.LayoutManagerProxy.getContentOfArea(LayoutManagerProxy.java:84) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.photon.core.app.layout.ApplicationLayoutManager.getContentOfArea(ApplicationLayoutManager.java:82) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.photon.core.app.layout.AbstractLayoutManagerBasedLayoutHTMLProvider.getContentOfArea(AbstractLayoutManagerBasedLayoutHTMLProvider.java:65) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.photon.core.app.layout.AbstractLayoutHTMLProvider.fillBody(AbstractLayoutHTMLProvider.java:167) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.photon.core.app.html.AbstractHTMLProvider.createHTML(AbstractHTMLProvider.java:212) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.photon.core.app.html.PhotonHTMLHelper.createHTMLResponse(PhotonHTMLHelper.java:114) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.photon.core.servlet.AbstractApplicationServlet.handleRequest(AbstractApplicationServlet.java:162) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.photon.core.servlet.AbstractUnifiedResponseServlet._run(AbstractUnifiedResponseServlet.java:522) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.photon.core.servlet.AbstractUnifiedResponseServlet.onPost(AbstractUnifiedResponseServlet.java:612) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at com.helger.web.servlets.scope.AbstractScopeAwareHttpServlet.doPost(AbstractScopeAwareHttpServlet.java:371) [ph-web-8.6.2.jar:8.6.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.29]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.29]
	at com.helger.web.servlets.scope.AbstractScopeAwareFilter.doFilter(AbstractScopeAwareFilter.java:128) [ph-web-8.6.2.jar:8.6.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.29]
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:537) [jersey-container-servlet-core-2.23.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:524) [jersey-container-servlet-core-2.23.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:461) [jersey-container-servlet-core-2.23.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.29]
	at com.helger.photon.core.servlet.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:116) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.29]
	at com.helger.photon.core.servlet.HttpoxyFilter.doFilter(HttpoxyFilter.java:62) [ph-oton-core-7.0.0-b3.jar:7.0.0-b3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.29]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.29]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.29]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.29]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.29]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.29]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.29]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.29]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.29]
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:850) [tomcat-coyote.jar:8.0.29]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674) [tomcat-coyote.jar:8.0.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-coyote.jar:8.0.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-coyote.jar:8.0.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.29]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: com.sun.xml.ws.util.ServiceConfigurationError: com.sun.xml.ws.api.policy.PolicyResolverFactory: Provider com.sun.xml.ws.policy.parser.WsitPolicyResolverFactory is specified in jar:file:/data0/web/tomcat/lib/webservices-rt.jar!/META-INF/services/com.sun.xml.ws.api.policy.PolicyResolverFactorybut could not be instantiated: java.lang.ClassCastException: Cannot cast com.sun.xml.ws.policy.parser.WsitPolicyResolverFactory to com.sun.xml.ws.api.policy.PolicyResolverFactory
	at com.sun.xml.ws.util.ServiceFinder.fail(ServiceFinder.java:278) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.util.ServiceFinder.access$600(ServiceFinder.java:153) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.util.ServiceFinder$LazyIterator.next(ServiceFinder.java:527) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.util.ServiceFinder$CompositeIterator.next(ServiceFinder.java:422) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.api.policy.PolicyResolverFactory.create(PolicyResolverFactory.java:61) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:162) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:358) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	... 67 more
Caused by: java.lang.ClassCastException: Cannot cast com.sun.xml.ws.policy.parser.WsitPolicyResolverFactory to com.sun.xml.ws.api.policy.PolicyResolverFactory
	at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_66]
	at com.sun.xml.ws.util.ServiceFinder$LazyIterator.next(ServiceFinder.java:523) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.util.ServiceFinder$CompositeIterator.next(ServiceFinder.java:422) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.api.policy.PolicyResolverFactory.create(PolicyResolverFactory.java:61) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:162) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:358) ~[jaxws-rt-2.2.9-b14002.jar:2.2.1-1]
	... 67 more
```

**Comment by phax** [comment]
Yes, this happens when Metro is in the class path.
Remove "jaxb*.jar" and "jaxws*.jar" from the application class path and it will work
