### ISSUE TITLE
Invalid backend 'sql' provided

### ISSUE THREAD

**Issue by ThiemeNL** [phax/peppol-smp-server#60]
Hi,

First of all, thank you for make this SMP server publicly available.

I'm tring to use a mysql database as backend server inside a docker. 
I changed the smp-server.properties file with:
```
# The backend to be used. Can either be "sql" or "xml". Any other value will result in a startup error
# Default is XML so that the tests run flawlessly
smp.backend = sql
```
And included a mysql driver and enabled other sql properties inside the smp-server.properties file. 
But I'm not able to start the server because of this error:
```
09-Dec-2017 18:37:00.553 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [com.helger.peppol.smpserver.servlet.SMPWebAppListener]
 com.helger.commons.exception.InitializationException: Invalid backend 'sql' provided. Supported ones are: [xml]
        at com.helger.peppol.smpserver.domain.SMPMetaManager.initBackendFromConfiguration(SMPMetaManager.java:344)
        at com.helger.peppol.smpserver.servlet.SMPWebAppListener.initGlobals(SMPWebAppListener.java:110)
        at com.helger.photon.core.servlet.AbstractWebAppListenerMultiApp.afterContextInitialized(AbstractWebAppListenerMultiApp.java:113)
        at com.helger.photon.core.servlet.WebAppListener.contextInitialized(WebAppListener.java:531)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1141)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
I'm using version 5.0.3

Best Regard,
Thieme

**Comment by ThiemeNL** [comment]
When I look at it again with fresh eyes, I see that there's also a peppol-smp-server-webapp-sql version. So I will give that a try.

**Comment by phax** [comment]
Yes please. I needed to separate the different backends, because the XML-version with contained EclipseLink caused issues with WildFly.... So the backend is basically fixed, except if you want to provide your owhn data storage :)
