### ISSUE TITLE
Socket timed out exception while connecting to SMP when doing multiple transactions

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-smp-server#63]
Performed some 20 requests
Notice that only 19 worked and one out of 20 transactions failed with "Request send error Socket operation timed out before it could be completed"
Observed this stack trace in the request process log:
...
Caused by: com.ibm.b2b.comms.http.sender.exception.ConnectFailedException: Connection Failure for connection properties [RemoteHost:B-cddd3d2e86e5fbd4cdabf61d42da5c79.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu,RemotePort:80,Localhost:9.113.28.69]
at com.ibm.b2b.comms.http.sender.impl.channelfw.Worker.doConnectAndSend(Worker.java:112)
at com.ibm.b2b.comms.http.sender.impl.SenderImpl.send(SenderImpl.java:54)
at Proxy88cb390e_44d8_4241_b85b_34cf8126c2dd.send(Unknown Source)
at Proxy88cb390e_44d8_4241_b85b_34cf8126c2dd.send(Unknown Source)
at Proxy57bf273e_2ad9_4144_a944_09eaa56d866c.send(Unknown Source)
at com.ibm.b2b.comms.emb.handler.impl.HTTPSenderHandler.process(HTTPSenderHandler.java:94)
... 16 more
Caused by: java.net.SocketTimeoutException: Socket operation timed out before it could be completed
at com.ibm.b2b.ws.tcpchannel.internal.ConnectChannelSelector.checkForTimeouts(ConnectChannelSelector.java:230)
at com.ibm.b2b.ws.tcpchannel.internal.ChannelSelector.run(ChannelSelector.java:237)
... 1 more

**Comment by dhixon** [comment]
We believe that this can be handled on our side.  Closing this issue.

**Comment by phax** [comment]
@dhixon can you elaborate a bit more, where this happens?
Is this the SMP->SML connection or the SMP->PD connection or public GET API?

**Comment by dhixon** [comment]
Hi Philip,
 
The socket timeout we decided we should just wait longer for a response from the SMP.  We upped the wait to 60 seconds.  I went ahead and closed the issue (#63).
 
Currently we are having another issue on our SMP that is linked to the SMK.  When we create a service group, we get an error that the service group could not be created.  Turns out that the service is actually created in the SMK, but the SMP thinks that it has not been created.  We actually came up with a workaround to then turn off the SMK link, create the service group in the SMP, and then turn the link to the SMK back on.  
 
We are trying to get a log file with some error information.  There is no catalina.out file in the tomcat/logs directory, though there are catalina_<date>.log files.  Do you know how to configure logging in Tomcat so that it will capture the errors in the SMP?
 
Thanks,
 
David HixonIBM Advanced Communications Technical LeadIBM Commerce Division - IBM US(720) 342-8547Tie 575-7375Email:  dhixon@us.ibm.com
 
 
----- Original message -----From: Philip Helger <notifications@github.com>To: phax/peppol-smp-server <peppol-smp-server@noreply.github.com>Cc: dhixon <dhixon@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [phax/peppol-smp-server] Socket timed out exception while connecting to SMP when doing multiple transactions (#63)Date: Tue, Feb 6, 2018 10:13 AM 
@dhixon can you elaborate a bit more, where this happens?Is this the SMP->SML connection or the SMP->PD connection or public GET API?

**Comment by phax** [comment]
Please send me the catalina.YYYHHMM.out file for today by email. Thanks.

The configuration of your Tomcat logging heavily depends on your version: see https://tomcat.apache.org/tomcat-8.0-doc/logging.html for details.
